'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,Compass} from 'lucide-react';
import {Button} from '../components/ui/button';
import {Progress} from '../components/ui/progress';
import {broadQuestions,specificQuestions,domainScores,recommendedDomains,domains,type Bi} from './taxonomy';
type Props={en:boolean;answers:Record<string,number>;setAnswers:(a:Record<string,number>)=>void;selectedDomains:string[];setDomains:(ids:string[])=>void;index:number;setIndex:(i:number)=>void;onFinish:()=>void;onExit:()=>void};
export default function Assessment({en,answers,setAnswers,selectedDomains,setDomains,index,setIndex,onFinish,onExit}:Props){
 const t=(b:Bi)=>b[en?1:0];const [pending,setPending]=useState<number|null>(null);const broadCount=broadQuestions.length;const isBroad=index<broadCount;const isDomains=index===broadCount;const detail=specificQuestions(selectedDomains,answers);const q=isBroad?broadQuestions[index]:detail[Math.min(Math.max(0,index-broadCount-1),detail.length-1)];const progress=isBroad?index/broadCount*100:(index-broadCount-1)/Math.max(1,detail.length)*100;const recommendations=recommendedDomains(answers);const board=domainScores(answers);
 useEffect(()=>{document.getElementById('assessment-heading')?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'})},[q?.id,isDomains]);
 function respond(value:number){if(pending!==null||!q)return;setPending(value);const next={...answers,[q.id]:value};setTimeout(()=>{setAnswers(next);setPending(null);if(isBroad)setIndex(index+1);else if(index-broadCount>=specificQuestions(selectedDomains,next).length)onFinish();else setIndex(index+1)},160)}
 const labels:Bi[]=[['مو أنا أبدًا','Not like me'],['يشبهني قليلًا','A little like me'],['إلى حد ما','Somewhat like me'],['يشبهني كثيرًا','Very like me'],['هذا أنا تمامًا','Exactly like me']];
 if(isDomains)return <section className="domain-reveal"><div className="phase-label"><Compass size={18}/>{t(['المرحلة ٢ من ٣ · الصورة العامة','Stage 2 of 3 · The bigger picture'])}</div><h1 id="assessment-heading" tabIndex={-1}>{t(['ميولك الأقوى تبدو هنا.','Your strongest interests appear here.'])}</h1><p className="intro">{t(['هذه إشارات أولية من اهتماماتك، وليست اختيارًا لتخصص. اختر مجالًا إلى ثلاثة لنفهم تفضيلاتك داخله.','These are early interest signals, not a major recommendation. Choose one to three domains to explore in more depth.'])}</p><p className="muted">{recommendations.length?t(['المجالات المعلّمة هي الأعلى ضمن الإجابات المتاحة. المجالات المتعادلة متساوية دون أفضلية تقنية أو مالية.','Highlighted domains have the highest available signals. Tied domains are equal, with no technology or pay preference.']):t(['ما عندنا إشارات قوية كافية بعد. يمكنك اختيار مجال يثير فضولك، أو الرجوع للأسئلة.','There are not enough strong signals yet. Choose a domain you’re curious about, or revisit your answers.'])}</p><div className="domain-grid">{board.map(({domain,score})=><button key={domain.id} aria-pressed={selectedDomains.includes(domain.id)} className={`domain-choice ${selectedDomains.includes(domain.id)?'selected':''}`} disabled={!selectedDomains.includes(domain.id)&&selectedDomains.length>=3} onClick={()=>setDomains(selectedDomains.includes(domain.id)?selectedDomains.filter(x=>x!==domain.id):[...selectedDomains,domain.id])}><span className="domain-choice-head"><strong>{t(domain.name)}</strong><span>{selectedDomains.includes(domain.id)?<Check size={19}/>:score===null?'—':`${score}%`}</span></span><span className="domain-bar" aria-hidden="true"><i style={{width:`${score??0}%`}}/></span><small>{score===null?t(['لم تتحدد بعد','Not yet known']):recommendations.includes(domain.id)?t(['ضمن ميولك الأعلى · إشارة أولية','Among your top interests · early signal']):t(['إشارة أولية من إجابة واحدة','Early signal from one answer'])}</small></button>)}</div><div className="domain-actions"><Button variant="outline" onClick={()=>setIndex(broadCount-1)}>{t(['راجع إجاباتي','Review answers'])}</Button><span>{selectedDomains.length} / 3</span><Button disabled={!selectedDomains.length} onClick={()=>setIndex(broadCount+1)}>{t(['نفهم ميولي أكثر','Explore my interests further'])}</Button></div></section>;
 if(!q)return <section className="empty"><h1>{t(['خلّنا نختار مجالًا نستكشفه','Let’s choose a domain to explore'])}</h1><Button onClick={()=>setIndex(broadCount)}>{t(['عرض المجالات','View domains'])}</Button></section>;
 const domain=domains.find(d=>d.id===q.domain)!;
 return <section className="assessment"><div className="assessment-meta"><button disabled={pending!==null} onClick={()=>index>0?setIndex(index-1):onExit()}>{en?<ArrowLeft/>:<ArrowRight/>}{t(['السابق','Back'])}</button><span>{isBroad?index+1:index-broadCount} / {isBroad?broadCount:detail.length}</span></div><div className="phase-label"><Compass size={17}/>{isBroad?t(['المرحلة ١ من ٣ · اكتشاف اهتماماتك','Stage 1 of 3 · Discover your interests']):t(['المرحلة ٣ من ٣ · فهم أعمق','Stage 3 of 3 · A closer look'])}</div><Progress value={progress}/><div className="question" key={q.id}><span className="eyebrow">{isBroad?t(['فكّر في نفسك، مو في تخصصك','Think about yourself, not your major']):t(domain.name)}</span><h1 id="assessment-heading" tabIndex={-1}>{t(q.text)}</h1><p>{t(['قد إيش تشبهك العبارة؟ ما فيه إجابة أفضل من غيرها.','How much does this sound like you? No answer is better than another.'])}</p><div className="answer-list">{labels.map((label,i)=><button aria-pressed={answers[q.id]===i+1} key={i} disabled={pending!==null} className={pending===i+1||answers[q.id]===i+1?'selected':''} onClick={()=>respond(i+1)}><span>{String(i+1).padStart(2,'0')}</span>{t(label)}<span className="answer-circle">{(pending===i+1||answers[q.id]===i+1)&&<Check size={16}/>}</span></button>)}<button className={`unknown-option ${answers[q.id]===0?'selected':''}`} disabled={pending!==null} onClick={()=>respond(0)}><span>?</span>{t(['ما أعرف / ما عندي تفضيل','I don’t know / no preference'])}</button></div><p className="privacy-note">{isBroad?t(['نستكشف ٢١ عائلة مهنية بالتساوي. «ما أعرف» لا تُحسب كرفض.','We explore 21 career families equally. “I don’t know” does not count as rejection.']):t(['هذه الأسئلة تخص المجالات التي اخترتها فقط. «ما أعرف» تُستبعد من الحساب.','These questions cover only your selected domains. Unknown answers are excluded from scoring.'])}</p></div></section>
}
