import {careers as legacyCareers} from './legacy-careers';
import {domains,broadQuestions,specificQuestions,type Bi} from './taxonomy';
export {domains,families,activeQuestions,domainScores,recommendedDomains,broadQuestions,specificQuestions,ENGINE_VERSION} from './taxonomy';
export type {Bi} from './taxonomy';
export type Career={id:string;name:Bi;domain:string;family:string;tagline:Bi;skills:string[];math:number;code:number;remote:number;months:string;weights:number[];profile:number[];tasks:Bi[];project:Bi;resource:string;regulated:boolean};
type Seed=[string,string,string,number[],boolean?];
const catalog:Record<string,Seed[]>={
health:[['medicine','الطب','Medicine',[5,5,5,5,5,2],true],['nursing','التمريض','Nursing',[5,5,4,5,3,1],true],['pharmacy','الصيدلة','Pharmacy',[3,1,5,3,4,3],true],['dentistry','طب الأسنان','Dentistry',[5,5,4,3,5,1],true],['physical-therapy','العلاج الطبيعي','Physical Therapy',[5,2,4,3,4,2],true],['radiology','تقنيات الأشعة','Radiologic Technology',[4,3,4,4,3,2],true],['laboratory-sciences','علوم المختبرات','Laboratory Sciences',[1,4,5,3,3,5],true],['public-health','الصحة العامة','Public Health',[2,1,4,2,3,5]],['nutrition','التغذية','Nutrition',[4,1,4,2,3,4],true]],
business:[['accountant','المحاسبة','Accounting',[5,4,1,3,2,3]],['finance-analyst','التحليل المالي','Financial Analysis',[4,5,2,3,3,5]],['marketing-specialist','التسويق','Marketing',[2,3,5,3,4,3]],['business-manager','إدارة الأعمال','Business Management',[3,3,3,5,4,3]],['sales-specialist','المبيعات','Sales',[2,3,4,3,5,2]],['economist','الاقتصاد','Economics',[3,5,2,2,2,5]],['business-founder','تأسيس مشروع تجاري','Business Founder',[3,4,4,4,5,3]],['supply-chain-manager','إدارة سلسلة الإمداد','Supply Chain Management',[4,3,2,5,4,3]]],
engineering:[['mechanical-engineer','الهندسة الميكانيكية','Mechanical Engineering',[5,3,2,2,3,3],true],['electrical-engineer','الهندسة الكهربائية','Electrical Engineering',[3,5,2,2,3,2],true],['civil-engineer','الهندسة المدنية','Civil Engineering',[2,2,5,2,3,1],true],['chemical-engineer','الهندسة الكيميائية','Chemical Engineering',[2,2,2,5,3,1],true],['industrial-engineer','الهندسة الصناعية','Industrial Engineering',[3,2,3,2,5,1]],['aerospace-engineer','هندسة الطيران','Aerospace Engineering',[4,3,1,2,3,5],true]],
technology:[['software-engineer','هندسة البرمجيات','Software Engineering',[5,2,2,2,1,2]],['data-analyst','تحليل البيانات','Data Analysis',[2,5,1,1,1,2]],['data-scientist','علوم البيانات','Data Science',[4,5,1,1,1,5]],['data-engineer','هندسة البيانات','Data Engineering',[5,4,2,4,1,3]],['bi-analyst','ذكاء الأعمال','Business Intelligence',[2,5,1,1,1,1]],['security-analyst','الأمن السيبراني','Cybersecurity',[3,3,5,4,2,2]],['network-engineer','هندسة الشبكات','Network Engineering',[2,2,3,5,4,1]],['hardware-engineer','هندسة عتاد الحاسب','Computer Hardware Engineering',[3,2,2,4,5,2]],['ai-engineer','هندسة الذكاء الاصطناعي','AI Engineering',[5,5,2,2,1,5]],['cloud-engineer','الهندسة السحابية','Cloud Engineering',[4,2,4,5,2,2]],['systems-engineer','هندسة الأنظمة','Systems Engineering',[3,2,4,5,4,1]]],
law:[['lawyer','المحاماة','Law',[5,5,5,3,4,1],true],['policy-analyst','تحليل السياسات','Policy Analysis',[4,5,2,5,3,5]],['legal-researcher','البحث القانوني','Legal Research',[5,5,1,3,2,5]],['mediator','الوساطة','Mediation',[3,3,4,3,5,1],true]],
education:[['primary-teacher','تعليم المرحلة الابتدائية','Primary Education',[5,2,5,4,4,1],true],['secondary-teacher','التعليم المتخصص','Subject Teaching',[2,5,4,4,3,2],true],['instructional-designer','التصميم التعليمي','Instructional Design',[2,4,3,5,4,5]],['special-education','التربية الخاصة','Special Education',[4,3,5,4,5,2],true]],
arts:[['graphic-designer','التصميم الجرافيكي','Graphic Design',[5,3,3,1,3,2]],['ux-designer','تصميم تجربة المستخدم','UX Design',[3,5,2,1,1,1]],['animator','الرسوم المتحركة','Animation',[4,2,5,1,3,4]],['interior-designer','التصميم الداخلي','Interior Design',[4,3,1,5,2,2]],['fine-artist','الفنون الجميلة','Fine Arts',[5,1,2,3,5,3]],['filmmaker','صناعة الأفلام','Filmmaking',[3,2,5,2,4,5]]],
media:[['journalist','الصحافة','Journalism',[5,5,3,2,3,3]],['communications-specialist','العلاقات العامة والتواصل','Public Relations & Communication',[4,4,4,5,2,4]],['content-producer','إنتاج المحتوى','Content Production',[3,4,3,2,5,5]],['presenter','التقديم الإعلامي','Presenting',[4,3,5,3,4,4]]],
science:[['biologist','علوم الأحياء','Biology',[5,3,1,2,5,3]],['chemist','الكيمياء','Chemistry',[2,5,3,3,5,1]],['physicist','الفيزياء','Physics',[1,2,5,5,4,1]],['field-researcher','البحث العلمي الميداني','Field Research',[4,2,3,2,4,5]]],
social:[['sociologist','علم الاجتماع','Sociology',[5,3,4,4,3,5]],['anthropologist','الأنثروبولوجيا','Anthropology',[3,5,5,2,4,5]],['community-researcher','البحث المجتمعي','Community Research',[4,4,5,4,5,3]]],
psychology:[['psychologist','علم النفس المهني','Professional Psychology',[5,3,5,3,2,5],true],['behavioral-researcher','البحث السلوكي','Behavioral Research',[3,5,3,3,3,5]],['organizational-psychologist','علم النفس التنظيمي','Organizational Psychology',[3,4,4,1,5,4]],['school-psychologist','علم النفس المدرسي','School Psychology',[5,3,5,5,1,5],true]],
languages:[['translator','الترجمة التحريرية','Translation',[5,5,3,2,2,5]],['interpreter','الترجمة الشفهية','Interpreting',[5,5,2,1,5,2]],['editor','التحرير الأدبي','Literary Editing',[3,3,5,4,1,5]],['creative-writer','الكتابة الإبداعية','Creative Writing',[3,2,5,5,1,4]]],
architecture:[['architect','العمارة','Architecture',[5,5,3,2,5,3],true],['urban-planner','التخطيط الحضري','Urban Planning',[3,3,5,4,5,2]],['landscape-designer','تصميم المواقع الطبيعية','Landscape Design',[4,3,4,5,4,3]],['construction-manager','إدارة التشييد','Construction Management',[3,5,2,1,5,5]]],
environment:[['agriculture-specialist','الإنتاج الزراعي','Agricultural Production',[5,5,3,3,5,2]],['environmental-specialist','العلوم البيئية','Environmental Science',[3,5,4,5,2,3]],['conservation-specialist','حماية الطبيعة','Conservation',[4,5,5,3,2,4]],['food-scientist','علوم الغذاء','Food Science',[3,2,2,4,5,2]]],
hospitality:[['hospitality-manager','إدارة الضيافة','Hospitality Management',[5,3,3,2,5,5]],['tourism-guide','الإرشاد السياحي','Tour Guiding',[5,3,5,1,5,2],true],['event-planner','تنظيم الفعاليات','Event Planning',[4,5,3,2,5,4]],['chef','فنون الطهي','Culinary Arts',[3,2,3,5,5,3]]],
sports:[['sports-coach','التدريب الرياضي','Sports Coaching',[5,4,4,5,3,5],true],['sports-analyst','تحليل الأداء الرياضي','Sports Performance Analysis',[3,5,3,4,5,2]],['sports-organizer','إدارة الأنشطة الرياضية','Sports Event Management',[3,3,5,4,3,4]],['fitness-trainer','تدريب اللياقة','Fitness Training',[5,5,2,5,3,5],true]],
trades:[['electrician','الفني الكهربائي','Electrician',[5,5,3,2,5,5],true],['mechanic','الصيانة الميكانيكية','Mechanical Maintenance',[5,2,5,2,5,5]],['carpenter','النجارة','Carpentry',[5,1,2,5,5,5]],['metal-fabricator','تشكيل المعادن','Metal Fabrication',[5,2,3,5,5,5]],['hvac-technician','التبريد والتكييف','HVAC Technician',[5,4,5,2,5,5],true]],
aviation:[['pilot','قيادة الطائرات','Pilot',[5,4,3,5,5,1],true],['air-traffic-controller','المراقبة الجوية','Air Traffic Control',[1,5,2,5,5,5],true],['aircraft-technician','صيانة الطائرات','Aircraft Maintenance',[1,3,5,5,4,4],true],['flight-dispatcher','ترحيل الرحلات الجوية','Flight Dispatch',[2,5,3,5,4,5],true]],
logistics:[['logistics-planner','تخطيط النقل','Logistics Planning',[5,4,3,4,4,4]],['inventory-planner','تخطيط المخزون','Inventory Planning',[3,5,3,4,2,5]],['procurement-specialist','المشتريات','Procurement',[3,3,5,3,3,3]],['operations-coordinator','تنسيق العمليات','Operations Coordination',[4,4,3,5,5,4]]],
public:[['public-administrator','الإدارة العامة','Public Administration',[4,5,3,1,5,4]],['community-coordinator','تنسيق المبادرات المجتمعية','Community Coordination',[5,4,5,2,3,4]],['emergency-coordinator','تنسيق الاستجابة للطوارئ','Emergency Response Coordination',[4,4,4,5,4,3],true],['service-quality-specialist','جودة الخدمات العامة','Public Service Quality',[4,5,3,1,4,5]]],
entrepreneurship:[['venture-founder','تأسيس المشاريع','Venture Creation',[5,5,5,4,2,1]],['social-entrepreneur','ريادة الأعمال الاجتماعية','Social Entrepreneurship',[5,4,4,3,5,2]],['small-business-operator','تشغيل مشروع صغير','Small Business Operations',[3,2,4,5,3,5]]]
};
const generatedCareers:Career[]=domains.flatMap(domain=>(catalog[domain.id]||[]).map(([id,ar,en,profile,regulated])=>({id,name:[ar,en] as Bi,domain:domain.id,family:domain.name[1],tagline:[`استكشف كيف تتحول ميولك إلى عمل في ${ar}.`,`Explore how your interests connect to ${en.toLowerCase()}.`] as Bi,skills:domain.skills,math:['engineering','science','business','technology'].includes(domain.id)?4:2,code:domain.id==='technology'?4:1,remote:['languages','media','arts','technology','business','law'].includes(domain.id)?4:2,months:'—',weights:profile,profile,tasks:[domain.traits[profile.indexOf(Math.max(...profile))],['تعاون مع مختصين، ووثّق قراراتك وملاحظاتك.','Collaborate with practitioners and document decisions and observations.'],['راجع جودة العمل وتعلّم من التغذية الراجعة.','Review the work and learn from feedback.']] as Bi[],project:[`استكشف حالة تعليمية في ${ar}، وحدد المشكلة واقترح خطوات وناقشها مع مختص؛ تجنب ممارسة أي عمل منظم دون تأهيل.`,`Explore a learning case in ${en.toLowerCase()}, identify the problem, propose steps, and discuss it with a practitioner; do not perform regulated work without qualification.`] as Bi,resource:domain.resource,regulated:!!regulated})));
export const careers:Career[]=generatedCareers.map(c=>{const old=legacyCareers.find(x=>x.id===c.id);return old?{...c,tagline:old.tagline,skills:old.skills,tasks:old.tasks,project:old.project,resource:old.resource,math:old.math,code:old.code,remote:old.remote,months:old.months}:c});
export function fit(c:Career,answers:Record<string,number>){const broad=answers['broad:'+c.domain];const eligible=specificQuestions([c.domain],answers);const observed=eligible.filter(q=>(answers[q.id]??0)>0);if(observed.length<3)return {score:null,evidence:observed.length,total:eligible.length,contributions:[] as {trait:number;answer:number;target:number;fit:number}[]};const contributions=observed.map(q=>({trait:q.trait!,answer:answers[q.id],target:c.profile[q.trait!],fit:100-Math.abs(answers[q.id]-c.profile[q.trait!])*25}));const detail=contributions.reduce((n,x)=>n+x.fit,0)/contributions.length;return {score:Math.round(broad>0?((broad-1)*25)*.4+detail*.6:detail),evidence:observed.length,total:eligible.length,contributions};}
export function score(c:Career,answers:Record<string,number>){return fit(c,answers).score??0}
export function rankedCareers(answers:Record<string,number>,selected:string[]){return careers.filter(c=>selected.includes(c.domain)&&fit(c,answers).score!==null).sort((a,b)=>score(b,answers)-score(a,answers)||a.id.localeCompare(b.id))}
export function isComplete(answers:Record<string,number>,selected:string[]){return selected.length>0&&broadQuestions.every(q=>q.id in answers)&&specificQuestions(selected,answers).every(q=>q.id in answers)}
