export type Bi=[string,string];
export type Career={id:string;name:Bi;family:string;tagline:Bi;skills:string[];math:number;code:number;remote:number;months:string;weights:number[];tasks:Bi[];project:Bi;resource:string};
export const families:Bi[]=[['البيانات','Data'],['البرمجيات','Software'],['الذكاء الاصطناعي','AI'],['الأمن السيبراني','Cybersecurity'],['السحابة','Cloud'],['الأنظمة','Systems']];
export const careers:Career[]=[
{id:'data-analyst',name:['محلل بيانات','Data Analyst'],family:'Data',tagline:['حوّل الأرقام إلى قرارات تصنع فرقًا.','Turn numbers into decisions that matter.'],skills:['Excel','SQL','Statistics','Power BI','Python','Portfolio'],math:3,code:2,remote:4,months:'6–9',weights:[5,2,3,4],tasks:[['تنظيف البيانات واكتشاف الأنماط','Clean data and uncover patterns'],['بناء لوحات تساعد الفريق على اتخاذ القرار','Build dashboards that support decisions'],['شرح النتائج لأصحاب المصلحة','Explain findings to stakeholders']],project:['حلّل مبيعات متجر، وحدد أسباب تراجع الإيرادات، ثم اعرض توصياتك في لوحة تفاعلية.','Analyze store sales, investigate falling revenue, and present recommendations in an interactive dashboard.'],resource:'https://learn.microsoft.com/en-us/training/powerplatform/power-bi'},
{id:'data-scientist',name:['عالم بيانات','Data Scientist'],family:'Data',tagline:['اكتشف ما تخبئه البيانات عن الغد.','Discover what data tells us about tomorrow.'],skills:['Python','Statistics','SQL','Machine Learning','Experiments','Portfolio'],math:5,code:4,remote:4,months:'12–18',weights:[5,4,2,3],tasks:[['صياغة فرضيات قابلة للاختبار','Frame testable hypotheses'],['تدريب نماذج وتقييم دقتها','Train and evaluate models'],['تفسير النتائج وحدودها','Communicate results and limitations']],project:['ابنِ نموذجًا لتوقع الطلب، وقارن أداءه بخط أساس بسيط.','Build a demand forecast and compare it against a simple baseline.'],resource:'https://scikit-learn.org/stable/tutorial/index.html'},
{id:'data-engineer',name:['مهندس بيانات','Data Engineer'],family:'Data',tagline:['ابنِ البنية التي تثق بها البيانات.','Build foundations that data can rely on.'],skills:['SQL','Python','Databases','Pipelines','Cloud','Portfolio'],math:3,code:5,remote:4,months:'9–15',weights:[4,5,1,5],tasks:[['بناء خطوط تدفق بيانات','Build data pipelines'],['فحص الجودة والأداء','Check quality and performance'],['إدارة مستودعات البيانات','Manage data warehouses']],project:['اجمع بيانات عامة ونظفها وحمّلها إلى مستودع مع فحوص جودة.','Ingest public data into a warehouse with quality checks.'],resource:'https://www.postgresql.org/docs/current/tutorial.html'},
{id:'bi-analyst',name:['محلل ذكاء أعمال','BI Analyst'],family:'Data',tagline:['اربط أداء اليوم بقرارات الغد.','Connect today’s performance to tomorrow’s decisions.'],skills:['Excel','SQL','KPIs','Power BI','Storytelling','Portfolio'],math:2,code:2,remote:4,months:'6–9',weights:[4,1,4,4],tasks:[['تعريف مؤشرات الأداء','Define performance metrics'],['تصميم تقارير تشغيلية','Design operational reports'],['توضيح فرص تحسين الأعمال','Identify business improvements']],project:['صمم تقرير أداء شهريًا يوضح تغير المبيعات ومسبباته.','Create a monthly performance report explaining sales changes.'],resource:'https://learn.microsoft.com/en-us/training/powerplatform/power-bi'},
{id:'software-engineer',name:['مهندس برمجيات','Software Engineer'],family:'Software',tagline:['حوّل فكرة في بالك إلى شيء يستخدمه الناس.','Turn an idea into something people use.'],skills:['JavaScript','HTML & CSS','React','APIs','Testing','Portfolio'],math:2,code:5,remote:5,months:'9–12',weights:[2,5,4,3],tasks:[['بناء واجهات وخدمات','Build interfaces and services'],['اختبار السلوك وإصلاح الأعطال','Test behavior and fix bugs'],['مراجعة الكود مع الفريق','Review code with the team']],project:['ابنِ تطبيق تتبع عادات يدعم الجوال وإمكانية الوصول واختبارات للسلوك الأساسي.','Build an accessible habit tracker with mobile support and behavior tests.'],resource:'https://developer.mozilla.org/en-US/docs/Learn_web_development'},
{id:'ai-engineer',name:['مهندس ذكاء اصطناعي','AI Engineer'],family:'AI',tagline:['امنح المنتجات قدرات جديدة.','Give products new capabilities.'],skills:['Python','Linear Algebra','Machine Learning','Evaluation','Deployment','Portfolio'],math:5,code:5,remote:4,months:'12–18',weights:[5,5,3,2],tasks:[['تجهيز بيانات التدريب','Prepare training data'],['تقييم النماذج والأخطاء','Evaluate models and errors'],['دمج النماذج في المنتجات','Integrate models into products']],project:['ابنِ مصنف نصوص وقس الدقة والأخطاء على بيانات منفصلة.','Build a text classifier and evaluate it on held-out data.'],resource:'https://pytorch.org/tutorials/'},
{id:'security-analyst',name:['محلل أمن سيبراني','Security Analyst'],family:'Cybersecurity',tagline:['كن خطوة أمام المخاطر.','Stay one step ahead of risk.'],skills:['Networks','Linux','Security Basics','Logs','Incident Response','Portfolio'],math:2,code:3,remote:3,months:'9–12',weights:[3,3,1,5],tasks:[['مراقبة التنبيهات الأمنية','Monitor security alerts'],['تحليل الحوادث','Investigate incidents'],['توثيق إجراءات الحماية','Document protective controls']],project:['حلّل سجلات مختبر محلي واكتب تقرير استجابة لحادث افتراضي.','Analyze local lab logs and write a simulated incident report.'],resource:'https://owasp.org/www-project-web-security-testing-guide/'},
{id:'cloud-engineer',name:['مهندس سحابة','Cloud Engineer'],family:'Cloud',tagline:['صمّم خدمات تستمر بالنمو.','Design services that keep growing.'],skills:['Linux','Networks','Cloud','Containers','Automation','Portfolio'],math:2,code:4,remote:4,months:'9–15',weights:[2,4,2,5],tasks:[['إعداد خدمات سحابية','Configure cloud services'],['مراقبة الاعتمادية والتكلفة','Monitor reliability and cost'],['أتمتة النشر','Automate deployments']],project:['انشر خدمة تجريبية مع مراقبة وتوثيق للتكلفة وخطة استعادة.','Deploy a trial service with monitoring, costs, and a recovery plan.'],resource:'https://learn.microsoft.com/en-us/training/azure/'},
{id:'systems-engineer',name:['مهندس أنظمة','Systems Engineer'],family:'Systems',tagline:['اجعل الأجزاء تعمل كمنظومة واحدة.','Make the pieces work as one system.'],skills:['Linux','Networks','Scripting','Monitoring','Recovery','Portfolio'],math:2,code:3,remote:2,months:'9–12',weights:[2,3,1,5],tasks:[['إدارة الأنظمة والصلاحيات','Manage systems and access'],['استكشاف الأعطال','Troubleshoot failures'],['اختبار النسخ والاستعادة','Test backup and recovery']],project:['أنشئ مختبر خوادم محليًا ووثّق خطة استعادة مجرّبة.','Build a local server lab with a tested recovery plan.'],resource:'https://ubuntu.com/tutorials'}];
