export type Bi=[string,string];
export type Domain={id:string;name:Bi;broad:Bi;traits:Bi[];skills:string[];resource:string};
const d=(id:string,name:Bi,broad:Bi,traits:Bi[],skills:string[],resource:string):Domain=>({id,name,broad,traits,skills,resource});
export const domains:Domain[]=[
d('health',['الصحة والطب','Health & Medicine'],['أشعر بالإنجاز عندما أساعد شخصًا على تحسين صحته وراحته.','I feel fulfilled helping someone improve their health and wellbeing.'],[
['أرتاح للتعامل المباشر مع المرضى.','I feel comfortable working directly with patients.'],['أستطيع التعامل مع مشاهد الدم والإجراءات السريرية.','I feel able to handle blood and clinical procedures.'],['أحب التعمق في الأحياء والكيمياء.','I enjoy exploring biology and chemistry.'],['أستطيع الحفاظ على تركيزي في مواقف عاجلة وضاغطة.','I can stay focused in urgent, stressful situations.'],['أنا مستعد لمسار دراسة وتدريب رسمي طويل.','I am willing to follow a long formal study and training path.'],['أفضل البحث والوقاية على الإجراءات العلاجية المباشرة.','I prefer research and prevention over direct clinical procedures.']],['Biology','Communication','Ethics','Evidence','Supervised learning','Reflection'],'https://www.who.int/health-topics'),
d('engineering',['الهندسة','Engineering'],['أستمتع بفهم القوى والحركة وكيف يمكن بناء شيء يعمل بأمان.','I enjoy understanding forces, motion, and how to build something that works safely.'],[
['أحب فهم الآلات والحركة الميكانيكية.','I enjoy machines and mechanical motion.'],['تثير اهتمامي الكهرباء والدوائر والطاقة.','Electricity, circuits, and energy interest me.'],['أحب تصميم المنشآت والبنية التحتية والعمل الميداني.','I enjoy structures, infrastructure, and fieldwork.'],['أهتم بتحويل المواد والتفاعلات إلى عمليات صناعية.','I am interested in industrial materials and chemical processes.'],['أحب تحسين جودة الإنتاج وتنظيم العمليات.','I enjoy improving production quality and processes.'],['تثير اهتمامي ديناميكا الطيران والمركبات الجوية.','Aircraft and flight dynamics interest me.']],['Mathematics','Physics','Design','Safety','Modeling','Project'],'https://ocw.mit.edu/'),
d('technology',['الحوسبة والتقنية','Computing & Technology'],['أحب تقسيم مهمة معقدة إلى خطوات منطقية وابتكار أداة تسهّلها.','I enjoy breaking a complex task into logical steps and inventing a tool to simplify it.'],[
['أستمتع بكتابة البرامج وتجربة الكود.','I enjoy programming and experimenting with code.'],['أحب اكتشاف الأنماط والإحصاءات في البيانات.','I enjoy patterns and statistics in data.'],['أهتم بحماية الأنظمة والتحقيق في المخاطر الأمنية.','I am interested in protecting systems and investigating security risks.'],['أحب فهم الشبكات وكيف تتواصل الأجهزة.','I enjoy networks and how devices communicate.'],['أستمتع بفهم مكونات الأجهزة والعمل عليها.','I enjoy understanding and working with hardware.'],['أرغب في بناء نماذج تتعلم من البيانات وتقييمها.','I want to build and evaluate models that learn from data.']],['Logic','Computing foundations','Programming','Systems','Testing','Portfolio'],'https://developer.mozilla.org/en-US/docs/Learn_web_development'),
d('business',['الأعمال والمال','Business & Finance'],['أستمتع بفهم كيف تستخدم مؤسسة مواردها وتحقق قيمة مالية.','I enjoy understanding how an organization uses resources and creates financial value.'],[
['أحب تدقيق الحسابات وتتبع المعاملات بدقة.','I enjoy accurate accounts and transaction records.'],['أهتم بتقييم القرارات المالية والمخاطر.','I am interested in financial decisions and risk.'],['أحب فهم العملاء وتطوير رسائل تسويقية.','I enjoy understanding customers and marketing messages.'],['أستمتع بتنظيم فريق وتوزيع المسؤوليات.','I enjoy organizing teams and responsibilities.'],['أحب التفاوض والإقناع وبناء علاقات بيع.','I enjoy negotiation, persuasion, and sales relationships.'],['أهتم بتفسير سلوك الأسواق والاقتصاد.','I am interested in how markets and economies work.']],['Business basics','Numeracy','Communication','Ethics','Analysis','Case study'],'https://www.open.edu/openlearn/money-business'),
d('law',['القانون والسياسات العامة','Law & Public Policy'],['أحب فهم القواعد ومناقشة الحجج والدفاع عن قضية بأدلة.','I enjoy understanding rules, debating arguments, and defending a cause with evidence.'],[
['أستمتع بقراءة النصوص القانونية بدقة.','I enjoy carefully reading legal texts.'],['أحب صياغة حجج مكتوبة وواضحة.','I enjoy clear written arguments.'],['أرتاح للنقاش والمرافعة الشفهية.','I am comfortable with oral debate and advocacy.'],['أهتم بأثر السياسات على المجتمع.','I am interested in how policy affects society.'],['أحب الوساطة والوصول إلى اتفاق بين أطراف مختلفة.','I enjoy mediation and agreements between different parties.'],['أفضل البحث والتحليل على المواجهة المباشرة.','I prefer research and analysis to direct confrontation.']],['Reading','Reasoning','Writing','Ethics','Research','Case analysis'],'https://www.open.edu/openlearn/society-politics-law'),
d('education',['التعليم','Education'],['أستمتع بشرح فكرة ومساعدة شخص على اكتساب مهارة جديدة.','I enjoy explaining ideas and helping someone learn a new skill.'],[
['أستمتع بتعليم الأطفال الصغار.','I enjoy teaching young children.'],['أحب تبسيط موضوع للمتعلمين الأكبر سنًا.','I enjoy simplifying subjects for older learners.'],['أصبر على اختلاف سرعات التعلم.','I am patient with different learning paces.'],['أحب تصميم أنشطة ومواد تعليمية.','I enjoy designing learning activities and materials.'],['أهتم بدعم احتياجات تعلم متنوعة.','I am interested in supporting diverse learning needs.'],['أفضل البحث والتخطيط التعليمي على إدارة صف يومية.','I prefer educational research and planning to daily classroom management.']],['Learning theory','Communication','Lesson design','Inclusion','Supervised practice','Reflection'],'https://www.open.edu/openlearn/education-development'),
d('arts',['الفنون والتصميم','Arts & Design'],['أشعر بالحماس عند ابتكار شيء جميل بصريًا أو التعبير عن فكرة بصورة.','I feel excited creating something visually expressive or communicating an idea through images.'],[
['أحب الرسم والهوية البصرية وتكوين الصور.','I enjoy drawing, visual identity, and composition.'],['أهتم بكيفية تفاعل الناس مع المنتجات وسهولة استخدامها.','I care about how people interact with products and their usability.'],['أستمتع بالحركة وسرد القصص المصورة.','I enjoy motion and visual storytelling.'],['أحب تخطيط الألوان والمواد داخل المساحات.','I enjoy colors and materials within interior spaces.'],['أفضل التعبير الفني الحر على متطلبات العميل المحددة.','I prefer free artistic expression to a defined client brief.'],['أستمتع بالتصوير وصناعة المشاهد والأفلام.','I enjoy photography, scenes, and filmmaking.']],['Visual foundations','Sketching','Composition','Critique','Making','Portfolio'],'https://www.open.edu/openlearn/history-the-arts'),
d('media',['الإعلام والتواصل','Media & Communication'],['أحب إيصال قصة أو معلومة لجمهور بطريقة تؤثر فيه.','I enjoy communicating a story or idea to an audience in an engaging way.'],[
['أحب جمع المعلومات وإجراء المقابلات.','I enjoy gathering information and interviewing people.'],['أستمتع بالكتابة والتحرير والتحقق من الحقائق.','I enjoy writing, editing, and fact-checking.'],['أرتاح للظهور أو الحديث أمام جمهور.','I am comfortable presenting to an audience.'],['أحب بناء علاقات وتنسيق رسائل مؤسسية.','I enjoy relationships and organizational communication.'],['أستمتع بالإنتاج المرئي أو الصوتي.','I enjoy audio or visual production.'],['أحب متابعة تفاعل الجمهور وتحسين المحتوى.','I enjoy audience feedback and improving content.']],['Writing','Research','Ethics','Production','Audience','Portfolio'],'https://www.open.edu/openlearn/history-the-arts'),
d('science',['العلوم والبحث','Science & Research'],['أحب طرح سؤال واختبار تفسيره بتجربة وملاحظة دقيقة.','I enjoy asking a question and testing an explanation through observation and experiments.'],[
['أهتم بالكائنات الحية والأنظمة الحيوية.','Living organisms and biological systems interest me.'],['أحب دراسة المواد والتفاعلات الكيميائية.','I enjoy materials and chemical reactions.'],['أحب تفسير الظواهر بقوانين الفيزياء.','I enjoy explaining phenomena through physics.'],['أرتاح للرياضيات والتجريد.','I am comfortable with mathematics and abstraction.'],['أصبر على تكرار التجارب وتوثيق نتائجها.','I am patient with repeated experiments and documentation.'],['أفضل العمل الميداني على المختبر.','I prefer fieldwork to laboratory work.']],['Scientific method','Measurement','Statistics','Ethics','Experiment','Report'],'https://www.open.edu/openlearn/science-maths-technology'),
d('social',['العلوم الاجتماعية','Social Sciences'],['أشعر بالفضول تجاه المجتمعات وكيف تؤثر الظروف على حياة الناس.','I am curious about communities and how circumstances shape people’s lives.'],[
['أحب دراسة أنماط المجتمع والمؤسسات.','I enjoy studying social patterns and institutions.'],['أهتم بثقافات الناس وتاريخ حياتهم.','I am interested in cultures and lived histories.'],['أحب المقابلات والاستماع لتجارب مختلفة.','I enjoy interviews and different experiences.'],['أرتاح لتحليل الاستبيانات والبيانات الاجتماعية.','I am comfortable analyzing surveys and social data.'],['أريد العمل المباشر مع المجتمع.','I want direct community work.'],['أستمتع بالبحث النظري والكتابة الأكاديمية.','I enjoy theoretical research and academic writing.']],['Research methods','Listening','Ethics','Analysis','Field observation','Report'],'https://www.open.edu/openlearn/society-politics-law'),
d('psychology',['النفس والسلوك الإنساني','Psychology & Human Behavior'],['أحب فهم ما يشعر به الناس ولماذا يتصرفون بطرق مختلفة.','I enjoy understanding what people feel and why they behave differently.'],[
['أستمتع بالاستماع المتأني لمشاعر الناس.','I enjoy listening carefully to people’s feelings.'],['أهتم بتجارب علمية عن السلوك والإدراك.','I am interested in scientific experiments on behavior and cognition.'],['أستطيع الحفاظ على حدود مهنية عند سماع مشكلات صعبة.','I can maintain professional boundaries around difficult problems.'],['أهتم بنمو الأطفال وتعلمهم.','I am interested in children’s development and learning.'],['أحب فهم سلوك الأفراد داخل العمل.','I enjoy understanding behavior at work.'],['أنا مستعد لدراسة وتدريب رسميين ممتدين.','I am willing to complete extensive formal study and training.']],['Psychology foundations','Research','Ethics','Listening','Supervised learning','Reflection'],'https://www.open.edu/openlearn/health-sports-psychology'),
d('languages',['اللغات والأدب','Languages & Literature'],['أستمتع بالكلمات والقراءة واكتشاف المعاني بين لغات وثقافات مختلفة.','I enjoy words, reading, and meaning across languages and cultures.'],[
['أستمتع بتعلم لغات جديدة.','I enjoy learning new languages.'],['أحب نقل المعنى بدقة بين لغتين.','I enjoy conveying meaning accurately between languages.'],['أستمتع بالتحليل الأدبي والقراءة العميقة.','I enjoy literary analysis and close reading.'],['أحب الكتابة الإبداعية.','I enjoy creative writing.'],['أرتاح للترجمة الشفهية الفورية.','I am comfortable with real-time spoken interpretation.'],['أحب تدقيق النصوص وتحريرها.','I enjoy proofreading and editing.']],['Reading','Language practice','Writing','Culture','Revision','Portfolio'],'https://www.open.edu/openlearn/languages'),
d('architecture',['العمارة والبيئة المبنية','Architecture & Built Environment'],['أتخيل كيف يمكن تحسين المباني والأماكن التي نعيش فيها.','I imagine how to improve the buildings and places we live in.'],[
['أحب رسم الفراغات والتفكير ثلاثي الأبعاد.','I enjoy spatial drawing and three-dimensional thinking.'],['أهتم بتفاصيل البناء والمواد.','I am interested in construction details and materials.'],['أحب فهم حركة الناس داخل المدن.','I enjoy understanding how people move through cities.'],['أهتم بتصميم الحدائق والمساحات الخارجية.','I am interested in landscapes and outdoor spaces.'],['أصبر على مراجعات التصميم ومتطلبات السلامة.','I am patient with design revisions and safety requirements.'],['أحب إدارة التنفيذ في الموقع.','I enjoy managing on-site delivery.']],['Spatial thinking','Sketching','Materials','Safety','Model making','Portfolio'],'https://ocw.mit.edu/'),
d('environment',['الزراعة والبيئة','Agriculture & Environment'],['أهتم برعاية الطبيعة والكائنات وتحسين استخدام الموارد.','I care about living things, nature, and responsible resource use.'],[
['أستمتع بالنباتات والتربة والزراعة.','I enjoy plants, soil, and agriculture.'],['أحب العمل في الخارج وجمع عينات ميدانية.','I enjoy outdoor work and field sampling.'],['أهتم بحماية التنوع الحيوي.','I care about biodiversity conservation.'],['أحب قياس التلوث واستهلاك الموارد.','I enjoy measuring pollution and resource use.'],['أهتم بإنتاج الغذاء وتحسين جودته.','I am interested in food production and quality.'],['أستمتع بتوعية الناس بالاستدامة.','I enjoy communicating sustainability.']],['Ecology','Observation','Safety','Measurement','Field project','Report'],'https://www.fao.org/elearning/'),
d('hospitality',['الضيافة والسياحة','Hospitality & Tourism'],['أستمتع بصناعة تجربة مريحة ومميزة للضيوف والزوار.','I enjoy creating a welcoming and memorable experience for guests and visitors.'],[
['أحب استقبال ضيوف والتعامل مع احتياجاتهم.','I enjoy welcoming guests and meeting their needs.'],['أستمتع بتخطيط فعاليات وتجارب.','I enjoy planning events and experiences.'],['أحب التعرف على الأماكن والثقافات وشرحها.','I enjoy places, cultures, and explaining them.'],['أستمتع بإعداد الطعام وتطوير نكهاته.','I enjoy preparing food and developing flavors.'],['أرتاح لعمل متغير الأوقات وكثير الحركة.','I am comfortable with variable hours and active work.'],['أحب تنظيم عمليات الخدمة خلف الكواليس.','I enjoy organizing behind-the-scenes service operations.']],['Service','Communication','Safety','Planning','Supervised practice','Reflection'],'https://www.open.edu/openlearn/money-business'),
d('sports',['الرياضة والنشاط البدني','Sports & Physical Activity'],['أشعر بالحماس عند الحركة ومساعدة الآخرين على تحسين أدائهم البدني.','I feel energized by movement and helping others improve physical performance.'],[
['أحب تدريب الآخرين على مهارات حركية.','I enjoy coaching movement skills.'],['أهتم بفهم الجسم والأداء البدني.','I am interested in the body and physical performance.'],['أستمتع بتنظيم فرق ومنافسات.','I enjoy organizing teams and competitions.'],['أصبر على تدرج التحسن وتكرار التدريب.','I am patient with gradual progress and repeated training.'],['أحب تحليل أداء اللاعبين.','I enjoy analyzing athletic performance.'],['أفضل العمل العملي على العمل المكتبي.','I prefer practical work to desk work.']],['Movement science','Safety','Coaching','Planning','Supervised practice','Reflection'],'https://www.open.edu/openlearn/health-sports-psychology'),
d('trades',['الحرف والمهن الفنية','Skilled Trades & Technical Careers'],['أستمتع بإصلاح شيء بيدي ورؤية نتيجة عملية مباشرة.','I enjoy fixing something with my hands and seeing a practical result.'],[
['أحب استخدام الأدوات والعمل اليدوي الدقيق.','I enjoy tools and precise hands-on work.'],['أهتم بالتمديدات والدوائر الكهربائية.','I am interested in electrical wiring and circuits.'],['أحب فحص الآلات والمحركات وصيانتها.','I enjoy inspecting and maintaining machines and engines.'],['أستمتع بصنع قطع من الخشب أو المعدن.','I enjoy making things from wood or metal.'],['أرتاح للعمل الميداني مع الالتزام بإجراءات السلامة.','I am comfortable with fieldwork and safety procedures.'],['أفضل التعلم بالتدريب المهني والممارسة الموجهة.','I prefer apprenticeships and supervised practice.']],['Safety','Tools','Measurement','Technical drawings','Supervised practice','Work samples'],'https://www.apprenticeship.gov/career-seekers'),
d('aviation',['الطيران','Aviation'],['تجذبني المهام التي تجمع الدقة والتنقل والالتزام بإجراءات سلامة واضحة.','I am drawn to tasks combining precision, movement, and clear safety procedures.'],[
['أرغب في تشغيل الطائرات ضمن تدريب معتمد.','I want to operate aircraft through approved training.'],['أحب متابعة معلومات متعددة والتنسيق في الوقت الحقيقي.','I enjoy coordinating multiple information streams in real time.'],['أهتم بفحص الأنظمة الميكانيكية والكهربائية للطائرات.','I am interested in aircraft mechanical and electrical systems.'],['أرتاح لإجراءات دقيقة لا تحتمل الاختصار.','I am comfortable with strict procedures without shortcuts.'],['أتقبل جداول عمل متغيرة ومسؤوليات عالية.','I accept variable schedules and high responsibility.'],['أفضل التخطيط الأرضي على العمل في الطائرة.','I prefer ground planning to working in aircraft.']],['Safety culture','Communication','Mathematics','Procedures','Approved training','Review'],'https://www.icao.int/training'),
d('logistics',['اللوجستيات وسلاسل الإمداد','Logistics & Supply Chain'],['أحب ترتيب وصول الأشياء والأشخاص إلى المكان المناسب في الوقت المناسب.','I enjoy getting things and people to the right place at the right time.'],[
['أحب تخطيط حركة البضائع والنقل.','I enjoy planning transport and goods movement.'],['أستمتع بإدارة مخزون وتوقع الاحتياجات.','I enjoy inventory planning and anticipating needs.'],['أحب التفاوض مع الموردين.','I enjoy negotiating with suppliers.'],['أهتم بتحليل التأخير وتحسين العمليات.','I am interested in delays and process improvement.'],['أرتاح للتنسيق الميداني وحل المفاجآت.','I am comfortable with field coordination and surprises.'],['أحب العمل على الأنظمة والبيانات التشغيلية.','I enjoy operational systems and data.']],['Planning','Numeracy','Communication','Operations','Simulation','Case study'],'https://www.open.edu/openlearn/money-business'),
d('public',['الخدمة العامة','Public Service'],['أشعر بالإنجاز عند تحسين خدمة يحتاجها المجتمع والناس يوميًا.','I feel fulfilled improving services that communities need every day.'],[
['أحب مساعدة الناس على الوصول إلى خدماتهم.','I enjoy helping people access services.'],['أهتم بالعدالة والشفافية في الإجراءات.','I care about fair and transparent procedures.'],['أستمتع بتنسيق مبادرات مجتمعية.','I enjoy coordinating community initiatives.'],['أرتاح للاستجابة لمواقف طارئة وفق تدريب واضح.','I am comfortable responding to emergencies with clear training.'],['أحب تنظيم السجلات والإجراءات.','I enjoy records and administrative procedures.'],['أهتم بتقييم جودة الخدمات العامة.','I am interested in evaluating public service quality.']],['Service','Communication','Ethics','Procedures','Community project','Reflection'],'https://www.open.edu/openlearn/society-politics-law'),
d('entrepreneurship',['ريادة الأعمال','Entrepreneurship'],['أتحمس لاكتشاف حاجة وتجربة فكرة جديدة لتقديم قيمة للناس.','I am excited by discovering a need and trying a new idea that creates value for people.'],[
['أحب اختبار فكرة مع عملاء محتملين.','I enjoy testing an idea with potential customers.'],['أتقبل عدم اليقين وأجرب حلولًا صغيرة قبل التوسع.','I accept uncertainty and test small before scaling.'],['أستمتع بالبيع والتفاوض.','I enjoy selling and negotiation.'],['أحب متابعة التكلفة والتدفقات النقدية.','I enjoy costs and cash-flow planning.'],['أهتم بمشروع ذي أثر اجتماعي.','I am interested in a socially focused venture.'],['أفضل تشغيل مشروع قائم على تأسيس مشروع جديد.','I prefer operating an established venture to starting a new one.']],['Customer discovery','Experimentation','Budgeting','Ethics','Pilot','Review'],'https://www.sba.gov/business-guide')
];
export const families:Bi[]=domains.map(d=>d.name);
export const ENGINE_VERSION=2;
export type Question={id:string;text:Bi;domain:string;phase:'broad'|'specific';trait?:number;condition?:{id:string;min:number}};
export const broadQuestions:Question[]=domains.map(d=>({id:'broad:'+d.id,text:d.broad,domain:d.id,phase:'broad'}));
export function specificQuestions(ids:string[],answers:Record<string,number>={}):Question[]{return domains.filter(d=>ids.includes(d.id)).flatMap(d=>d.traits.map((text,i)=>({id:'specific:'+d.id+':'+i,text,domain:d.id,phase:'specific' as const,trait:i,...(d.id==='technology'&&i===5?{condition:{id:'specific:technology:0',min:3}}:{})}))).filter(q=>!q.condition||!(q.condition.id in answers)||answers[q.condition.id]===0||answers[q.condition.id]>=q.condition.min)}
export function activeQuestions(answers:Record<string,number>,ids:string[]=[]){return [...broadQuestions,...specificQuestions(ids,answers)]}
export function domainScores(answers:Record<string,number>){return domains.map(d=>({domain:d,score:answers['broad:'+d.id]>0?(answers['broad:'+d.id]-1)*25:null})).sort((a,b)=>(b.score??-1)-(a.score??-1));}
export function recommendedDomains(answers:Record<string,number>){const list=domainScores(answers).filter(x=>x.score!==null&&x.score>=50);if(!list.length)return [];const cutoff=list[Math.min(2,list.length-1)].score!;return list.filter(x=>x.score!>=cutoff).map(x=>x.domain.id)}
